### get employees
GET http://localhost:3000/api/employees

###
POST http://localhost:3000/api/employees
Content-Type: application/json

{
  "name": "John Doe",
  "salary": 1000
}

### Get employee by id
GET http://localhost:3000/api/employees/2

### Update an employee
PATCH http://localhost:3000/api/employees/2
Content-Type: application/json

{
  "name": "Ryan Ray",
  "salary": 500
}
